services:
  # ------------------------------------------------
  # Keycloak サーバ
  # ------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # 開発モードで簡単起動(インメモリDB等)
    command: ["start-dev"]

  # ------------------------------------------------
  # Next.js アプリ
  # ------------------------------------------------
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # ------------------------------------------------
  # NGINX (リバースプロキシや静的ファイル配信など)
  # ------------------------------------------------
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - nextjs
      - keycloak
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
